# Generated by Django 3.0.6 on 2020-07-16 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Ticket',
        ),
    ]
