# Generated by Django 3.0.6 on 2020-07-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20200728_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Severe', 'Severe')], default='Low', max_length=20),
        ),
    ]
