# Generated by Django 3.0.6 on 2020-08-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20200731_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='completed',
            field=models.BooleanField(db_column='Completed', default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='datecompletion',
            field=models.DateTimeField(blank=True, db_column='DateCompletion', null=True),
        ),
    ]
