# Generated by Django 3.0.6 on 2020-08-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20200818_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priorities',
            field=models.ManyToManyField(related_name='tickets', to='tickets.Priority'),
        ),
    ]
